#!/bin/bash
# Quick reference script for manual nginx activation on EC2
# DO NOT RUN THIS SCRIPT DIRECTLY - these are commands to run on EC2

echo "================================================"
echo "Manual Nginx Activation Commands for EC2"
echo "================================================"
echo ""
echo "These commands should be run ON THE EC2 INSTANCE after deployment."
echo "Do NOT run this script directly. Copy and paste commands individually."
echo ""
echo "1. SSH into EC2:"
echo "   ssh rollhub"
echo ""
echo "2. Link nginx config:"
echo "   sudo ln -sf /home/ubuntu/scifi-wiki/nginx_wiki.conf /etc/nginx/sites-enabled/wiki.conf"
echo ""
echo "3. Test nginx config:"
echo "   sudo nginx -t"
echo ""
echo "4. If test passes, reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "5. Check if port 5050 is listening:"
echo "   sudo netstat -tlnp | grep 5050"
echo ""
echo "6. Test the wiki:"
echo "   curl -I http://localhost:5050"
echo ""
echo "7. From your local machine, test:"
echo "   curl -I http://54.202.116.205:5050"
echo ""
echo "================================================"
